# mkAgent — the shared, reusable flake logic for launching ONE concrete agent
# in a microsandbox microVM. Many agents reuse this: each agent directory is a
# tiny flake that calls `launch.lib.mkAgent { ...its identity... }`.
#
# `nix run .#up` in an agent dir renders a Sandboxfile from these params and
# boots msb; inside the microVM the discourse-acp image runs the harness, which
# spawns the ACP agent (claude) and the @discourse/mcp server. Secrets are
# resolved at run time by secretspec (NEVER baked into Nix) and injected by msb
# scoped to the exact host allowed to use them.
{ nixpkgs }:

{ name ? ""                            # msb sandbox id (default: the bot username)
, discourseUrl                        # https://forum.example.com
, username                            # the bot's Discourse account
, owners ? [ ]                        # usernames allowed to !shutdown/!cancel/!rotate
, allowlist ? [ ]                     # extra usernames when respondTo = "allowlist"
, respondTo ? "owner-only"            # owner-only | allowlist | anyone | nobody
, agents ? 1                          # 1..32 agent subprocesses
, persona ? ""                        # explicit persona; "" -> harness uses the bot's Discourse bio
, personaFromBio ? true               # when persona is "", derive it from the bot account's About Me
, agentCommand ? "claude-agent-acp"   # ACP agent runtime (goose / codex-acp also work)
, providerHost ? "api.anthropic.com"  # the agent runtime's LLM egress host
, extraAllow ? [ ]                    # extra egress hosts (e.g. an image CDN)
, memory ? 2048                       # MiB
, cpus ? 2
, image ? "discourse-acp:latest"
, discourseAcpDir ? "../../discourse-acp"  # harness repo (for build-image)
}:

let
  lib = nixpkgs.lib;
  systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
  forAll = f: lib.genAttrs systems (s: f nixpkgs.legacyPackages.${s});

  hostOf = url:
    let m = builtins.match "[a-z]+://([^/:]+).*" url;
    in if m == null then url else builtins.head m;

  forumHost = hostOf discourseUrl;
  allowHosts = [ forumHost providerHost ] ++ extraAllow;
  ownersCsv = lib.concatStringsSep "," owners;
  allowlistCsv = lib.concatStringsSep "," allowlist;
  sandboxName = if name == "" then username else name;

  # microsandbox project manifest, derived entirely from the params above.
  sandboxfileText = ''
    # Generated by Nix (discourse-acp-sandbox lib.mkAgent) — do not edit by hand.
    sandboxes:
      ${sandboxName}:
        image: ${image}
        memory: ${toString memory}
        cpus: ${toString cpus}
        workdir: /workspace
        scripts:
          start: discourse-acp run
        network:
          allow:
  '' + lib.concatMapStrings (h: "        - ${h}\n") allowHosts;

  mkUp = pkgs: pkgs.writeShellApplication {
    name = "up";
    runtimeInputs = [ pkgs.bash pkgs.coreutils ];
    text = ''
      # 1. Materialize the manifest for msb.
      printf '%s' ${lib.escapeShellArg sandboxfileText} > ./Sandboxfile
      command -v msb >/dev/null 2>&1 || { echo "error: 'msb' (microsandbox) not on PATH" >&2; exit 1; }
      command -v secretspec >/dev/null 2>&1 || { echo "error: 'secretspec' not on PATH (see secretspec.toml)" >&2; exit 1; }
      # 2. Boot the microVM under secretspec, which resolves the declared secrets
      #    (secretspec.toml) from your provider and puts them in the environment;
      #    msb then injects each as a host-scoped --secret. No secret in Nix/disk.
      echo ">> booting '${sandboxName}' as @${username} (forum ${forumHost})"
      exec secretspec run -- msb run ${sandboxName} \
        --env DISCOURSE_URL=${lib.escapeShellArg discourseUrl} \
        --env DISCOURSE_API_USERNAME=${lib.escapeShellArg username} \
        --env DISCOURSE_ACP_AGENT_OWNER=${lib.escapeShellArg ownersCsv} \
        --env DISCOURSE_ACP_RESPOND_TO=${lib.escapeShellArg respondTo} \
        --env DISCOURSE_ACP_RESPOND_TO_ALLOWLIST=${lib.escapeShellArg allowlistCsv} \
        --env DISCOURSE_ACP_AGENTS=${toString agents} \
        --env DISCOURSE_ACP_AGENT_COMMAND=${lib.escapeShellArg agentCommand} \
        --env DISCOURSE_ACP_SYSTEM_PROMPT=${lib.escapeShellArg persona} \
        --env DISCOURSE_ACP_PERSONA_FROM_BIO=${if personaFromBio then "true" else "false"} \
        --secret DISCOURSE_API_KEY@${forumHost} \
        --secret CLAUDE_CODE_OAUTH_TOKEN@${providerHost}
    '';
  };

  mkBuild = pkgs: pkgs.writeShellApplication {
    name = "build-image";
    runtimeInputs = [ pkgs.bash pkgs.coreutils ];
    text = ''
      src="''${DISCOURSE_ACP_DIR:-${discourseAcpDir}}"
      [ -f "$src/Dockerfile" ] || { echo "no Dockerfile at '$src' (set DISCOURSE_ACP_DIR)" >&2; exit 1; }
      command -v docker >/dev/null 2>&1 || { echo "docker not on PATH" >&2; exit 1; }
      command -v msb >/dev/null 2>&1 || { echo "msb not on PATH" >&2; exit 1; }
      echo ">> docker build ${image} (context: $src)"
      docker build -t ${image} "$src"
      tar="$(mktemp -t discourse-acp-XXXXXX).tar"; trap 'rm -f "$tar"' EXIT
      echo ">> docker save + msb image load"
      docker save ${image} -o "$tar"
      msb image load "$tar" --tag ${image}
      echo "done: ${image} is in the microsandbox image cache."
    '';
  };

  mkSimple = pkgs: appName: body: pkgs.writeShellApplication {
    name = appName; runtimeInputs = [ pkgs.bash ];
    text = ''command -v msb >/dev/null 2>&1 || { echo "msb not on PATH" >&2; exit 1; }; ${body}'';
  };

  mkDevShell = pkgs: pkgs.mkShell {
    packages = [ pkgs.jq ];
    shellHook = ''
      echo "agent '${sandboxName}' — @${username} on ${forumHost}"
      echo "  external tools on PATH: docker (build), msb (microsandbox), secretspec"
      echo "  secrets: declared in secretspec.toml; set them with 'secretspec set <NAME>'"
      echo "  nix run .#build-image   ·   nix run .#up   ·   nix run .#logs   ·   nix run .#down"
    '';
  };

  app = program: { type = "app"; inherit program; };
in
{
  apps = forAll (pkgs: {
    build-image = app "${mkBuild pkgs}/bin/build-image";
    up = app "${mkUp pkgs}/bin/up";
    down = app "${mkSimple pkgs "down" "exec msb stop ${sandboxName}"}/bin/down";
    logs = app "${mkSimple pkgs "logs" "exec msb logs ${sandboxName}"}/bin/logs";
    default = app "${mkUp pkgs}/bin/up";
  });
  devShells = forAll (pkgs: { default = mkDevShell pkgs; });
  packages = forAll (pkgs: { sandboxfile = pkgs.writeText "Sandboxfile" sandboxfileText; });
}
